version: '3.8'
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8761:8761
  zuul-server:
    image: zuul-server
    container_name: zuul-server
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - MYSQL_SERVER=db
    restart: on-failure
    depends_on:
      - eureka-server
      - db
    ports:
      - 9092:9092
  advert-service:
    image: advert-service
#    container_name: advert-service
    build:
      context: ./advert-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - MYSQL_SERVER=db
      - ZUUL_SERVER=zuul-server
    restart: on-failure
    depends_on:
      - eureka-server
      - zuul-server
      - db
    ports:
      - 9093
  front-end:
    image: front-end
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - eureka-server
      - zuul-server
      - advert-service
      - db
    ports:
      - 9091:80
    links:
      - zuul-server
  db:
    image: 'mysql:latest'
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass
    restart: on-failure
    ports:
      - 3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro